# Generated by Django 5.0.2 on 2024-02-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetup',
            old_name='show_searh',
            new_name='show_search',
        ),
    ]
